# src/ApiBundle/Resources/config/validation.yml
ApiBundle\Entity\User:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
              fields: username
              message: "user.show_error_username_taken"
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
              fields: email
              message: "user.show_error_email_taken"
    properties:
        firstname:
            - NotBlank:
                  message: "user.show_error_firstname"
        username:
            - Regex:
                  pattern: '/^[a-z0-9_-]{3,16}$/'
                  match:   true
                  message: "user.show_error_username_policy"
        password:
            - Regex:
                  pattern: '/^([a-zA-Z0-9@*#]{8,15})$/'
                  match:   true
                  message: "user.show_error_password_policy"
        email:
            - Email:
                  message: "user.show_error_email"
                  checkMX: false
        dob:
            - Date:
                  message: "user.show_error_dob"
        roles:
            - Type:
                  type: array
                  message: The value {{ value }} is not a valid {{ type }}.
            - Choice:
                  choices:  ['ROLE_USER', 'ROLE_API']
                  message:  "user.show_error_role"
